server:
    port: 8083
zuul:
  routes:
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      url: http://localhost:8081/spring-security-oauth-server/oauth
  Servlet30WrapperFilter:
    pre:
      disable:true