server:
    port: 8081
    tomcat:
      accesslog:
        enabled: true
    servlet:
      context-path: /spring-security-oauth-server
      session:
        cookie:
          name: UISESSION

spring:
  datasource:
    url: jdbc:mysql://localhost/demodb?createDatabaseIfNotExist=true
    username: user
    password: password
    platform: mysql
    initialization-mode: always  
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false    
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
################### JavaMail Configuration ##########################
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: sweinhartdev@gmail.com  
    password: dvaqcpjijujfeame
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000              

support:
  email: sweinhart@prokarma.com

#    5am every day
purge:
  cron:
    expression: 0 0 5 * * ?

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: false
  hbm2ddl:
    auto: update
    
google:
  recaptcha:
    key: 
      site: 6LfaHiITAAAAAAgZBHl4ZUZAYk5RlOYTr6m2N34X
      secret: 6LfaHiITAAAAANpDTA_Zflwib95IhDqg2SNRLt4U
      
logging: 
  level:
    org.org.springframework: INFO 
    